# Generated by Django 2.2.4 on 2019-08-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newexpense', '0002_expense_date_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='user',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
